-- =====================================================
-- CAMPAIGNS SCHEMA ENHANCEMENT MIGRATION
-- =====================================================
-- Run this in Supabase SQL Editor to add missing fields
-- and sample data to the campaigns table

-- Step 1: Add UTM tracking fields to campaigns table
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS utm_source VARCHAR(100);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS utm_medium VARCHAR(100);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS utm_campaign VARCHAR(100);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS utm_content VARCHAR(100);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS utm_term VARCHAR(100);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS utm_url TEXT;

-- Step 2: Add campaign goals and targeting fields
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS target_audience TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS goals TEXT;

-- Step 3: Add performance metrics fields
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS leads INTEGER DEFAULT 0 CHECK (leads >= 0);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS demos INTEGER DEFAULT 0 CHECK (demos >= 0);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS revenue DECIMAL(12,2) DEFAULT 0 CHECK (revenue >= 0);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS roi DECIMAL(5,2) DEFAULT 0 CHECK (roi >= 0);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100);

-- Step 4: Add analytics tracking fields
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS total_clicks INTEGER DEFAULT 0 CHECK (total_clicks >= 0);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS conversions INTEGER DEFAULT 0 CHECK (conversions >= 0);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS conversion_rate DECIMAL(5,2) DEFAULT 0 CHECK (conversion_rate >= 0 AND conversion_rate <= 100);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS cost_per_click DECIMAL(10,2) DEFAULT 0 CHECK (cost_per_click >= 0);

-- Step 5: Update status constraint to include 'paused'
ALTER TABLE campaigns DROP CONSTRAINT IF EXISTS campaigns_status_check;
ALTER TABLE campaigns ADD CONSTRAINT campaigns_status_check 
    CHECK (status IN ('planning', 'active', 'paused', 'completed', 'cancelled'));

-- Step 6: Add field comments
COMMENT ON COLUMN campaigns.utm_source IS 'UTM source parameter for campaign tracking';
COMMENT ON COLUMN campaigns.utm_medium IS 'UTM medium parameter for campaign tracking';
COMMENT ON COLUMN campaigns.utm_campaign IS 'UTM campaign parameter for campaign tracking';
COMMENT ON COLUMN campaigns.utm_content IS 'UTM content parameter for campaign tracking';
COMMENT ON COLUMN campaigns.utm_term IS 'UTM term parameter for campaign tracking';
COMMENT ON COLUMN campaigns.utm_url IS 'Generated UTM tracking URL for the campaign';
COMMENT ON COLUMN campaigns.target_audience IS 'Target audience description for the campaign';
COMMENT ON COLUMN campaigns.goals IS 'Campaign goals and objectives';
COMMENT ON COLUMN campaigns.leads IS 'Total leads generated by the campaign';
COMMENT ON COLUMN campaigns.demos IS 'Total demos generated by the campaign';
COMMENT ON COLUMN campaigns.revenue IS 'Total revenue generated by the campaign';
COMMENT ON COLUMN campaigns.roi IS 'Return on investment percentage';
COMMENT ON COLUMN campaigns.progress IS 'Campaign completion progress (0-100)';
COMMENT ON COLUMN campaigns.total_clicks IS 'Total clicks on campaign UTM links';
COMMENT ON COLUMN campaigns.conversions IS 'Total conversions from campaign';
COMMENT ON COLUMN campaigns.conversion_rate IS 'Conversion rate percentage';
COMMENT ON COLUMN campaigns.cost_per_click IS 'Average cost per click';

-- Step 7: Create performance indexes
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_campaigns_progress ON campaigns(progress);
CREATE INDEX IF NOT EXISTS idx_campaigns_roi ON campaigns(roi);
CREATE INDEX IF NOT EXISTS idx_campaigns_revenue ON campaigns(revenue);
CREATE INDEX IF NOT EXISTS idx_campaigns_start_date ON campaigns(start_date);
CREATE INDEX IF NOT EXISTS idx_campaigns_end_date ON campaigns(end_date);
CREATE INDEX IF NOT EXISTS idx_campaigns_utm_source ON campaigns(utm_source);
CREATE INDEX IF NOT EXISTS idx_campaigns_utm_medium ON campaigns(utm_medium);
CREATE INDEX IF NOT EXISTS idx_campaigns_utm_campaign ON campaigns(utm_campaign);

-- Step 8: Insert sample campaign data
-- (Replace 'your-user-id-here' with an actual user ID from your users table)
INSERT INTO campaigns (
    user_id, name, description, status, start_date, end_date, budget, spent,
    utm_source, utm_medium, utm_campaign, utm_content, utm_term, utm_url,
    target_audience, goals, leads, demos, revenue, roi, progress,
    total_clicks, conversions, conversion_rate, cost_per_click,
    created_at, updated_at
) VALUES 
(
    (SELECT id FROM users LIMIT 1), -- Use first available user
    'Q4 SaaS Podcast Outreach',
    'Target top SaaS podcasts for product launch awareness',
    'active',
    '2024-10-15',
    '2024-12-31',
    25000.00,
    12450.00,
    'influencer',
    'podcast',
    'q4-saas',
    'q4_saas_podcast_outreach',
    'saas',
    'https://fluencr.com/campaign/q4-podcast?utm_source=influencer&utm_medium=podcast&utm_campaign=q4-saas&utm_content=q4_saas_podcast_outreach&utm_term=saas',
    'SaaS founders, CTOs, and technical decision makers',
    'Brand awareness, Lead generation, Product launch visibility',
    24,
    12,
    48600.00,
    3.90,
    65,
    1247,
    23,
    1.84,
    2.15,
    NOW() - INTERVAL '2 months',
    NOW() - INTERVAL '1 day'
),
(
    (SELECT id FROM users LIMIT 1),
    'LinkedIn Creator Partnership',
    'Collaborate with B2B marketing thought leaders',
    'planning',
    '2024-11-01',
    '2025-01-31',
    15000.00,
    0.00,
    'influencer',
    'linkedin',
    'creator-partnership',
    'linkedin_creator_partnership',
    'b2b',
    'https://fluencr.com/campaign/linkedin-creators?utm_source=influencer&utm_medium=linkedin&utm_campaign=creator-partnership&utm_content=linkedin_creator_partnership&utm_term=b2b',
    'B2B marketing professionals, growth hackers, and business leaders',
    'Thought leadership, Brand credibility, Lead generation',
    0,
    0,
    0.00,
    0.00,
    15,
    0,
    0,
    0.00,
    0.00,
    NOW() - INTERVAL '1 month',
    NOW() - INTERVAL '2 days'
),
(
    (SELECT id FROM users LIMIT 1),
    'Newsletter Sponsorship Series',
    'Strategic placements in top B2B newsletters',
    'completed',
    '2024-08-01',
    '2024-09-30',
    18000.00,
    17250.00,
    'influencer',
    'newsletter',
    'sponsorship-series',
    'newsletter_sponsorship_series',
    'b2b',
    'https://fluencr.com/campaign/newsletter-series?utm_source=influencer&utm_medium=newsletter&utm_campaign=sponsorship-series&utm_content=newsletter_sponsorship_series&utm_term=b2b',
    'B2B professionals, startup founders, and industry experts',
    'Brand awareness, Lead generation, Thought leadership',
    31,
    18,
    89400.00,
    5.20,
    100,
    2156,
    31,
    1.44,
    1.25,
    NOW() - INTERVAL '4 months',
    NOW() - INTERVAL '1 month'
),
(
    (SELECT id FROM users LIMIT 1),
    'Industry Conference Speakers',
    'Partner with conference speakers for post-event content',
    'paused',
    '2024-09-15',
    '2024-11-15',
    12000.00,
    3200.00,
    'influencer',
    'youtube',
    'conference-speakers',
    'conference_speakers',
    'conference',
    'https://fluencr.com/campaign/conference-speakers?utm_source=influencer&utm_medium=youtube&utm_campaign=conference-speakers&utm_content=conference_speakers&utm_term=conference',
    'Conference attendees, industry professionals, and thought leaders',
    'Post-event engagement, Content creation, Lead generation',
    7,
    3,
    12900.00,
    4.00,
    25,
    456,
    7,
    1.54,
    2.80,
    NOW() - INTERVAL '3 months',
    NOW() - INTERVAL '1 week'
),
(
    (SELECT id FROM users LIMIT 1),
    'Tech Twitter Influencer Campaign',
    'Engage with tech Twitter influencers for product visibility',
    'active',
    '2024-12-01',
    '2025-02-28',
    8000.00,
    2400.00,
    'influencer',
    'twitter',
    'tech-twitter',
    'tech_twitter_campaign',
    'tech',
    'https://fluencr.com/campaign/tech-twitter?utm_source=influencer&utm_medium=twitter&utm_campaign=tech-twitter&utm_content=tech_twitter_campaign&utm_term=tech',
    'Tech enthusiasts, developers, and startup community',
    'Community engagement, Product feedback, Brand awareness',
    12,
    5,
    15600.00,
    6.50,
    40,
    789,
    12,
    1.52,
    1.80,
    NOW() - INTERVAL '2 weeks',
    NOW() - INTERVAL '1 day'
),
(
    (SELECT id FROM users LIMIT 1),
    'B2B Podcast Network Partnership',
    'Long-term partnership with B2B podcast network',
    'planning',
    '2025-01-15',
    '2025-06-15',
    50000.00,
    0.00,
    'influencer',
    'podcast',
    'b2b-podcast-network',
    'b2b_podcast_network',
    'b2b',
    'https://fluencr.com/campaign/b2b-podcast-network?utm_source=influencer&utm_medium=podcast&utm_campaign=b2b-podcast-network&utm_content=b2b_podcast_network&utm_term=b2b',
    'B2B executives, decision makers, and industry leaders',
    'Long-term brand building, Thought leadership, Lead generation',
    0,
    0,
    0.00,
    0.00,
    5,
    0,
    0,
    0.00,
    0.00,
    NOW() - INTERVAL '1 week',
    NOW()
);

-- Step 9: Verify the migration
SELECT 
    'Migration completed successfully!' as status,
    COUNT(*) as total_campaigns,
    COUNT(CASE WHEN status = 'active' THEN 1 END) as active_campaigns,
    COUNT(CASE WHEN status = 'planning' THEN 1 END) as planning_campaigns,
    COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_campaigns,
    COUNT(CASE WHEN status = 'paused' THEN 1 END) as paused_campaigns
FROM campaigns;
